# -*- mode: ruby -*-
# vi: set ft=ruby :

# Case-sensitive volume in host for building kernel
# HOST_BUILD_VOLUME = "/Volumes/AndroidBuild"

# This is the mount point for the sync_folders in the VM
SRCMOUNT = "/opt/src"
LOCALDEV = "/local-dev"
BLDMOUNT = "/build"

CWD = File.dirname(File.expand_path(__FILE__))

# -----------------------------------------------------------------------------
# Vagrant definition
# -----------------------------------------------------------------------------
Vagrant.require_version ">= 1.7.4"
Vagrant.configure("2") do |config|

  # disable rsyncing folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # common settings: ssh login
  #config.ssh.username = "vagrant"
  #config.ssh.forward_agent = true

  # -----------------------------------
  # 1. VM for ironic
  # -----------------------------------
  config.vm.define "ironic" do |ironic|
    ironic.vm.box = "ubuntu/xenial64"
    
    # shared folders
    ironic.vm.synced_folder ENV.fetch('LOCALDEVDIR', "../.."), "#{LOCALDEV}"
    ironic.vm.synced_folder "..", "#{SRCMOUNT}"
    # ironic.vm.synced_folder "#{HOST_BUILD_VOLUME}", "#{BLDMOUNT}"

    # provisioning
    ironic.vm.provision "shell", inline: <<-SCRIPT
      set -x
      # timezone
      export TZ=Asia/Shanghai
    
      # setup scripts
      cd #{LOCALDEV}/scripts/ubuntu16
      ./setup_box.sh
      ./setup_python.sh
      ./setup_rabbitmq.sh
      ./setup_keystone.sh
      ./setup_horizon.sh
      ./setup_ironic.sh
    SCRIPT

    # VirtualBox
    ironic.vm.hostname = "ironic"
    # ironic.vm.network "public_network", nic_type: "virtio", bridge: ""
    # ironic.vm.network "public_network", nic_type: "virtio", ip: "10.0.0.250", bridge: "en5"

    # -- tftp --
    # ironic.vm.network "forwarded_port", guest: 69, host: 69
    # -- dhcp(udp) and bootp(tcp) --
    # ironic.vm.network "forwarded_port", guest: 67,  host: 67
    # -- ironic --
    ironic.vm.network "forwarded_port", guest: 6385,  host: 6385
    # -- web-ui --
    ironic.vm.network "forwarded_port", guest: 8080,  host: 28080
    # -- keystone Identity service public endpoint, administrative endpoint --
    # ironic.vm.network "forwarded_port", guest: 5000,  host: 5000
    # ironic.vm.network "forwarded_port", guest: 35357, host: 35357
    # -- Message Broker (AMQP traffic) --
    # ironic.vm.network "forwarded_port", guest: 5672, host: 5672 
    # -- Compute API (nova-api) --
    # ironic.vm.network "forwarded_port", guest: 8774, host: 8774
    # ironic.vm.network "forwarded_port", guest: 6081, host: 6081

    ironic.vm.provider "virtualbox" do |vb|
      vb.name = "server-ironic"
      vb.cpus = 2
      vb.memory = 4096
      vb.default_nic_type = "virtio"
      vb.customize ['modifyvm', :id, '--description', 'VM for openstack-ironic']
     #vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    end
  end

end
